# Array Manipulation Routines
[Array Manipulation Routines](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

In [2]:
import numpy as np

## Basic Operations

[`np.copyto`](https://numpy.org/doc/stable/reference/generated/numpy.copyto.html#numpy.copyto)

Copies values from one array to another, brodcasting as necessary.

In [3]:
A = np.array([4, 5, 6])
B = [1, 2, 3]
np.copyto(A, B)
A

array([1, 2, 3])

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = [[4, 5, 6], [7, 8, 9]]
np.copyto(A, B)
A

array([[4, 5, 6],
       [7, 8, 9]])

[`np.shape`](https://numpy.org/doc/stable/reference/generated/numpy.shape.html#numpy.shape)

Return shape of an array.

In [5]:
np.shape(np.eye(3))

(3, 3)

In [6]:
np.shape([[1,3]])

(1, 2)

In [7]:
np.shape([0])

(1,)

In [8]:
np.shape(0)

()

In [9]:
a = np.array([(1, 2), (3, 4), (5, 6)],
                dtype=[('x', 'i4'), ('y', 'i4')])
print(np.shape(a))
print(a.shape)

(3,)
(3,)


## Changing array shape

[`np.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

Gives a new shape to an array without changing its data.

In [10]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [12]:
np.reshape(a, 6, order='F')

array([1, 4, 2, 5, 3, 6])

In [13]:
np.reshape(a, (3,-1)) # the unspeified value is infered to be 2

array([[1, 2],
       [3, 4],
       [5, 6]])

[`np.ravel`](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html)

Returns a contiguous flattened array.

In [14]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [16]:
np.ravel(x, order='F')

array([1, 4, 2, 5, 3, 6])

When `order` is 'A', it will preserve the array's 'C' or 'F' ordering:

In [17]:
np.ravel(x.T)

array([1, 4, 2, 5, 3, 6])

In [18]:
np.ravel(x.T, order='A')

array([1, 2, 3, 4, 5, 6])

Wher `order` is 'K', it will preserve orderings that are neither 'C' or 'F', but won't reverse axes:

In [19]:
a = np.arange(3)[::-1]; a

array([2, 1, 0])

In [20]:
a.ravel(order='C')

array([2, 1, 0])

In [21]:
a.ravel(order='K')

array([2, 1, 0])

In [22]:
a = np.arange(12).reshape(2,3,2).swapaxes(1,2); a

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [23]:
a.ravel(order='C')

array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11])

In [24]:
a.ravel(order='K')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

[`np.ndarray.flat`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flat.html#numpy.ndarray.flat)

A 1-D iterator over the array.

In [25]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
x.flat[3]

4

In [27]:
x.T.flat[3]

5

In [28]:
type(x.flat)

numpy.flatiter

An assignment example:

In [29]:
x.flat = 3; x

array([[3, 3, 3],
       [3, 3, 3]])

In [30]:
x.flat[[1,4]] = 1; x

array([[3, 1, 3],
       [3, 1, 3]])

[`np.ndarray.flatten`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten)

Return a copy of the array collepsed into one dimension.

In [31]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [32]:
a.flatten('F')

array([1, 3, 2, 4])

## Transpose-like operations

[`np.moveaxis`](https://numpy.org/doc/stable/reference/generated/numpy.moveaxis.html#numpy.moveaxis)

Move axes of an array to new positions. Other axes remain in their original order.

In [33]:
x = np.zeros((3, 4, 5))
x.shape

(3, 4, 5)

In [34]:
np.moveaxis(x, 0, -1).shape

(4, 5, 3)

In [35]:
np.moveaxis(x, -1, 0).shape

(5, 3, 4)

These all achieve the same result:

In [36]:
np.transpose(x).shape

(5, 4, 3)

In [37]:
np.swapaxes(x, 0, -1).shape

(5, 4, 3)

In [38]:
np.moveaxis(x, [0,1], [-1,-2]).shape

(5, 4, 3)

In [39]:
np.moveaxis(x, [0,1,2], [-1, -2, -3]).shape

(5, 4, 3)

more examples:

In [40]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [41]:
np.moveaxis(a, 0, -1)

array([[[ 0,  6],
        [ 1,  7]],

       [[ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11]]])

In [42]:
np.moveaxis(a, 1, 0)

array([[[ 0,  1],
        [ 6,  7]],

       [[ 2,  3],
        [ 8,  9]],

       [[ 4,  5],
        [10, 11]]])

[`np.rollaxis`](https://numpy.org/doc/stable/reference/generated/numpy.rollaxis.html)

Roll the specified axis backwards, until it lies in a given position.

In [43]:
a = np.ones((3,4,5,6))
np.rollaxis(a, 3, 1).shape

(3, 6, 4, 5)

In [44]:
np.rollaxis(a, 2).shape

(5, 3, 4, 6)

In [45]:
np.rollaxis(a, 1, 4).shape

(3, 5, 6, 4)

[`np.swapaxes`](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html)

Interchange two axes of an array.

In [46]:
x = np.array([[1,2,3]])
np.swapaxes(x, 0, 1)

array([[1],
       [2],
       [3]])

In [47]:
x = np.array([[[0,1], [2,3]], [[4,5], [6,7]]])
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

[`np.ndarray.T`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html#numpy.ndarray.T)

View of the transposed array.

In [49]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [50]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [51]:
a.T

array([1, 2, 3, 4])

[`np.transpose`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html#numpy.transpose)

Returns an array with axes transposed.

In [52]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [53]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [54]:
np.transpose(a)

array([1, 2, 3, 4])

In [57]:
a = np.ones((1, 2 ,3))
np.transpose(a, (1, 0, 2)).shape

(2, 1, 3)

In [59]:
a = np.ones((2,3,4,5))
np.transpose(a).shape

(5, 4, 3, 2)