# Array Manipulation Routines
[Array Manipulation Routines](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

In [1]:
import numpy as np

## Basic Operations

[`np.copyto`](https://numpy.org/doc/stable/reference/generated/numpy.copyto.html#numpy.copyto)

Copies values from one array to another, brodcasting as necessary.

In [2]:
A = np.array([4, 5, 6])
B = [1, 2, 3]
np.copyto(A, B)
A

array([1, 2, 3])

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = [[4, 5, 6], [7, 8, 9]]
np.copyto(A, B)
A

array([[4, 5, 6],
       [7, 8, 9]])

[`np.shape`](https://numpy.org/doc/stable/reference/generated/numpy.shape.html#numpy.shape)

Return shape of an array.

In [5]:
np.shape(np.eye(3))

(3, 3)

In [6]:
np.shape([[1,3]])

(1, 2)

In [7]:
np.shape([0])

(1,)

In [8]:
np.shape(0)

()

In [11]:
a = np.array([(1, 2), (3, 4), (5, 6)],
                dtype=[('x', 'i4'), ('y', 'i4')])
print(np.shape(a))
print(a.shape)

(3,)
(3,)


## Changing array shape

[`np.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

Gives a new shape to an array without changing its data.

In [18]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [20]:
np.reshape(a, 6, order='F')

array([1, 4, 2, 5, 3, 6])

In [22]:
np.reshape(a, (3,-1)) # the unspeified value is infered to be 2

array([[1, 2],
       [3, 4],
       [5, 6]])

[`np.ravel`](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html)

Returns a contiguous flattened array.

In [24]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [26]:
np.ravel(x, order='F')

array([1, 4, 2, 5, 3, 6])

When `order` is 'A', it will preserve the array's 'C' or 'F' ordering:

In [27]:
np.ravel(x.T)

array([1, 4, 2, 5, 3, 6])

In [28]:
np.ravel(x.T, order='A')

array([1, 2, 3, 4, 5, 6])

Wher `order` is 'K', it will preserve orderings that are neither 'C' or 'F', but won't reverse axes:

In [29]:
a = np.arange(3)[::-1]; a

array([2, 1, 0])

In [30]:
a.ravel(order='C')

array([2, 1, 0])

In [31]:
a.ravel(order='K')

array([2, 1, 0])

In [32]:
a = np.arange(12).reshape(2,3,2).swapaxes(1,2); a

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [33]:
a.ravel(order='C')

array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11])

In [34]:
a.ravel(order='K')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

[`np.ndarray.flat`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flat.html#numpy.ndarray.flat)

A 1-D iterator over the array.

In [36]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
x.flat[3]

4

In [39]:
x.T.flat[3]

5

In [40]:
type(x.flat)

numpy.flatiter

An assignment example:

In [42]:
x.flat = 3; x

array([[3, 3, 3],
       [3, 3, 3]])

In [44]:
x.flat[[1,4]] = 1; x

array([[3, 1, 3],
       [3, 1, 3]])

[`np.ndarray.flatten`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten)

Return a copy of the array collepsed into one dimension.

In [45]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [46]:
a.flatten('F')

array([1, 3, 2, 4])