# Array Creation Routines
[Array creation](https://numpy.org/doc/stable/reference/routines.array-creation.html)

In [2]:
import numpy as np

## From Shape or Value

[`numpy.empty()`](https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty)

Return a new array of given shape and type without initializing entries.


In [3]:
np.empty([2,2])

array([[2.12199579e-314, 8.89116236e-312],
       [2.60866661e-321, 3.79442416e-321]])

In [4]:
np.empty([2,2], dtype=int)

array([[1921211182, -142079190],
       [ 725937598, 1264223240]])

[`numpy.empty_like()`](https://numpy.org/doc/stable/reference/generated/numpy.empty_like.html#numpy.empty_like)

Return a new array with the same shape and type as a given array.

In [5]:
a = ([1,2,3], [4,5,6])
np.empty_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
a = ([1., 2., 3.], [4., 5., 6.])
np.empty_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

[`numpy.eye()`](https://numpy.org/doc/stable/reference/generated/numpy.eye.html)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [7]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [8]:
np.eye(3, k=1) # k is index of diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [9]:
np.eye(3, 5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

[`numpy.identity()`](https://numpy.org/doc/stable/reference/generated/numpy.identity.html)

Return the identity array. **The identity array is a square array with ones on the main diagonal and zeros elsewhere.**

In [10]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

[`numpy.ones()`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

Return a new array of given shape and type, filled with ones.

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [13]:
np.ones((2,1))

array([[1.],
       [1.]])

In [14]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

[`numpy.ones_like()`](https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html)

Return an array of zeros with the same shape and type as a given array.

In [15]:
x = np.arange(6)
x = x.reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
y = np.arange(3, dtype=float)
y

array([0., 1., 2.])

In [18]:
np.ones_like(y)

array([1., 1., 1.])

[`numpy.zeros()`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

Return a new array of given shape and type, filled with zeros.

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [21]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [22]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [23]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom type

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

[`numpy.zeros_like()`](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html)

Return an array of zeros with the same shape and type as a given array.

In [24]:
x = np.arange(6)
x = x.reshape((2,3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
y = np.arange(3, dtype=float)
y

array([0., 1., 2.])

In [26]:
np.zeros_like(y)

array([0., 0., 0.])

[`numpy.full()`](https://numpy.org/doc/stable/reference/generated/numpy.full.html)

Return a new array of given shape and type, filled with *fill_value*

In [27]:
np.full((2,2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [28]:
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [29]:
np.full((2,2), [1,2])

array([[1, 2],
       [1, 2]])

[`numpy.full_like()`](https://numpy.org/doc/stable/reference/generated/numpy.full_like.html)

Return a full array with the shape and type as a given array.

In [30]:
x = np.arange(6)
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

In [31]:
np.full_like(x, 0.1)

array([0, 0, 0, 0, 0, 0])

In [32]:
np.full_like(x, 0.1, dtype=np.double)

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [33]:
np.full_like(x, np.nan, dtype=np.double)

array([nan, nan, nan, nan, nan, nan])

In [34]:
y = np.arange(6, dtype=np.double)
np.full_like(y, 0.1)

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [35]:
y = np.zeros([2, 2, 3], dtype=int)
np.full_like(y, [0, 0, 255])

array([[[  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255]]])

## From existing data

[`numpy.array()`](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

Create an array.

In [36]:
np.array([1,2,3])

array([1, 2, 3])

In [37]:
np.array([1, 2, 3.0]) # upcasting

array([1., 2., 3.])

In [38]:
np.array([[1, 2], [3, 4]]) # more than one dimension

array([[1, 2],
       [3, 4]])

In [39]:
np.array([1,2,3], ndmin=2) # minimum 2 dimensions

array([[1, 2, 3]])

In [40]:
np.array([1, 2, 3], dtype=complex) # type provided

array([1.+0.j, 2.+0.j, 3.+0.j])

In [41]:
# data type consisting of more than one element
x = np.array([(1, 2), (3, 4)], dtype=[('a', '<i4'),('b', '<i4')])
x['a']

array([1, 3])

In [42]:
np.array(np.mat('1 2; 3 4')) # creating an array from sub-classes

array([[1, 2],
       [3, 4]])

In [43]:
np.array(np.mat('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

[`numpy.asarray()`](https://numpy.org/doc/stable/reference/generated/numpy.asarray.html)

Convert input into an array

In [44]:
np.asarray([1,2]) # converts list into an array

array([1, 2])

In [45]:
# if dtype is set, array is only copied if dtype does not match
a = np.asarray([1,2], dtype=np.float32) 
print(np.asarray(a, dtype=np.float32) is a)
print(np.asarray(a, dtype=np.float64) is a)

True
False


In [46]:
# contrary to asanyarray, ndarray subclasses are not passed through
print(issubclass(np.recarray, np.ndarray))
a = np.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(np.recarray)
print(np.asarray(a) is a)
print(np.asanyarray(a) is a)

True
False
True


[`numpy.asanyarray()`](https://numpy.org/doc/stable/reference/generated/numpy.asanyarray.html)

Convert the input to an ndarray, but pass ndarray subclasses through.

In [47]:
a = [1,2]
np.asanyarray(a)

array([1, 2])

In [48]:
a = np.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(np.recarray)
np.asanyarray(a) is a

True

[`numpy.ascontiguousarray()`](https://numpy.org/doc/stable/reference/generated/numpy.ascontiguousarray.html)

Return a contiguous array (ndim >= 1) in memory (C order)

In [49]:
x = np.arange(6).reshape(2,3)
np.ascontiguousarray(x, dtype=np.float32)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [50]:
x.flags['C_CONTIGUOUS']

True

[`numpy.copy()`](https://numpy.org/doc/stable/reference/generated/numpy.copy.html)

Return an array copy of given object

In [51]:
# Create an array x, with a reference y and copy z
x = np.array([1,2,3])
y = x
z = np.copy(x)

In [52]:
# Not that, when we modify x, y changes, but not z
x[0] = 10

x[0] == y[0]

True

In [53]:
x[0] == z[0]

False

In [54]:
# Note that, np.copy clears previously set WRITEABLE=False flag
a = np.array([1,2,3])
a.flags["WRITEABLE"] = False
b = np.copy(a)
b.flags["WRITEABLE"]

True

In [55]:
b[0] = 3
b

array([3, 2, 3])

Note that `np.copy()` is a shallow copy an will not copy object elements within arrays. This is mainly important for arrays containing Python objects. The new array will contain the same object which may lead to **surprises** if that object can be modified (is mutable).

In [56]:
a = np.array([1, 'm', [2,3,4]], dtype=object)
b = np.copy(a)
b[2][0] = 10
a

array([1, 'm', list([10, 3, 4])], dtype=object)

To ensure all elements within an `object` array are copied, use `copy.deepcopy()`

In [57]:
import copy
a = np.array([1, 'm', [2,3,4]], dtype=object)
c = copy.deepcopy(a)
c[2][0] = 10
c

array([1, 'm', list([10, 3, 4])], dtype=object)

In [58]:
a

array([1, 'm', list([2, 3, 4])], dtype=object)

[`numpy.frombuffer()`](https://numpy.org/doc/stable/reference/generated/numpy.frombuffer.html)

Interpret buffer as 1-dimensional array.

**NOTE**

If buffer has data that is not machine byte-order, this should be specified as a part of data
type `dtype` (example below).

In [59]:
# byte order example
buf = b'\x01\x02\x03\x04'
print()
dt = np.dtype(int)
dt = dt.newbyteorder('>')
(np.frombuffer(buf, dtype=int), # old byte order
np.frombuffer(buf, dtype=dt))   # new byte order

(array([67305985]), array([16909060]))


The data of resulting array will not be byteswapped, but interpreted correctly.

This function creates view into original object. This should be safe in general, but it may make
sense to copy the result when the original object is mutable or untrusted. 

In [60]:
s = b'hello world'
np.frombuffer(s, dtype='S1', count=5, offset=6)

array([b'w', b'o', b'r', b'l', b'd'], dtype='|S1')

In [61]:
np.frombuffer(b'\x01\x02', dtype=np.uint8)

array([1, 2], dtype=uint8)

In [62]:
np.frombuffer(b'\x01\x02\x03\x04\x05', dtype=np.uint8, count=3)

array([1, 2, 3], dtype=uint8)

[`numpy.fromfile()`](https://numpy.org/doc/stable/reference/generated/numpy.fromfile.html#numpy.fromfile)

Construct an array from data in a text or binary file.

A highly efficient way of reading binary datta with a known data-type, as well as parsing simply formatted text files. Data written using the *tofile* method can be read using this function.

**Examples**

Construct an ndarray:

In [63]:
dt = np.dtype([('time', [('min', np.int64), ('sec', np.int64)]),
               ('temp', float)])
x = np.zeros((1,), dtype=dt)
x['time']['min'] = 10; x['temp'] = 98.25
x

array([((10, 0), 98.25)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

In [64]:
import tempfile
fname = tempfile.mkstemp()[1]
x.tofile(fname)

In [65]:
np.fromfile(fname, dtype=dt)

array([((10, 0), 98.25)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

In [66]:
np.save(fname, x)
np.load(fname + '.npy')

array([((10, 0), 98.25)],
      dtype=[('time', [('min', '<i8'), ('sec', '<i8')]), ('temp', '<f8')])

[`numpy.fromfunction()`](https://numpy.org/doc/stable/reference/generated/numpy.fromfunction.html)

Construct an array by executing a function overe each coordinate. The resulting array therefore has a value `fn(x, y, z)` at coordinate `(x, y, z)`

In [67]:
np.fromfunction(lambda i, j: i, (2,2), dtype=float)

array([[0., 0.],
       [1., 1.]])

In [68]:
np.fromfunction(lambda i, j: j, (2,2), dtype=float)

array([[0., 1.],
       [0., 1.]])

In [69]:
np.fromfunction(lambda i, j: i == j, (3,3), dtype=float)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [70]:
np.fromfunction(lambda i, j: i + j, (3,3), dtype=int) 

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

[`numpy.fromiter()`](https://numpy.org/doc/stable/reference/generated/numpy.fromiter.html)

Create a new 1-dimensional array from an iterable.

In [71]:
iterable = (x*x for x in range(5))
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [81]:
iterable = ((x+1, x+2) for x in range(5))
np.fromiter(iterable, dtype=np.dtype((int, 2)))

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

[`numpy.fromstring()`](https://numpy.org/doc/stable/reference/generated/numpy.fromstring.html)

A new 1-D array initialized from text data in a string.

In [73]:
np.fromstring('1 2', dtype=int, sep=' ')

array([1, 2])

In [74]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

[`numpy.loadtxt()`](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html)

Load data from a text file. Each row in the text file must have the same number of values.

In [75]:
from io import StringIO # String behaves like a file object
c = StringIO("0 1\n2 3")
np.loadtxt(c)

array([[0., 1.],
       [2., 3.]])

In [76]:
d = StringIO("M 21 72\nnF 35 58")
np.loadtxt(d, dtype={'names': ('gender', 'age', 'weight'),
                     'formats': ('S1', 'i4', 'f4')})

array([(b'M', 21, 72.), (b'n', 35, 58.)],
      dtype=[('gender', 'S1'), ('age', '<i4'), ('weight', '<f4')])

In [77]:
c = StringIO("1,0,2\n3,0,4")
x, y = np.loadtxt(c, delimiter=',', usecols=(0, 2), unpack=True)
x

array([1., 3.])

In [78]:
y

array([2., 4.])

The converters argument is used to specify functions to preprocess the text prior to parsing. *converters* can be a dictionary that maps preprocessing functions to each column:

In [79]:
s = StringIO("1.168, 2.296\n3.141, 4.669\n")
conv = {
    0: lambda x: np.floor(float(x)), # conversion fn for column 0
    1: lambda x: np.ceil(float(x)), # conversion fn for column 1
}

np.loadtxt(s, delimiter=",", converters=conv)

array([[1., 3.],
       [3., 5.]])

*converters* can be a callable instead of dictionary, in which case it is applied to all columns:

In [80]:
s = StringIO("0xDE 0xAD\n0xC0 0xDE")
import functools
conv = functools.partial(int, base=16)
np.loadtxt(s, converters=conv)

array([[222., 173.],
       [192., 222.]])

This example shows how *converters* can be used to convert a field with a trailing minus sign into a negative number.

In [84]:
s = StringIO('10.01 31.25-\n19.22 64.31\n17.57- 63.94')
def conv(fld):
    return -float(fld[:1] if fld.endswith(b'-') else float(fld))

np.loadtxt(s, converters=conv)

array([[-10.01,  -3.  ],
       [-19.22, -64.31],
       [ -1.  , -63.94]])

Using a callable as the converter can be particulary useful for handling values with different formatting, e.g. floats with underscores:

In [85]:
s = StringIO("1 2.7 100_000")
np.loadtxt(s, converters=float)

array([1.0e+00, 2.7e+00, 1.0e+05])

This idea can be extended to automatically handle values specified in many different formats:

In [86]:
def conv(val):
    try:
        return float(val)
    except ValueError:
        return float.fromhex(val)

s = StringIO("1, 2.5, 3_000, 0b4, 0x1.4000000000000p+2")
np.loadtxt(s, delimiter=",", converters=conv, encoding=None)

array([1.0e+00, 2.5e+00, 3.0e+03, 1.8e+02, 5.0e+00])

Note that with the default `encoding="bytes"`, the inputs to the converter function are latin-1 encoded byte strings. To deactivate the implicit encoding prior to conversion, use `encoding=None`

In [87]:
s = StringIO('10.01 31.25-\n19.22 64.31\n17.57- 63.94')
conv = lambda x: -float(x[:1]) if x.endswith('-') else float(x)
np.loadtxt(s, converters=conv, encoding=None)

array([[10.01, -3.  ],
       [19.22, 64.31],
       [-1.  , 63.94]])

Support for quoted fields is enabled with the *quotechar* parameter. Comment and delimiter characters are ignored when they appear within a quoted item delineated by *quotechar*:

In [88]:
s = StringIO('"alpha, #42", 10.0\n"beta, #64", 2.0\n')
dtype = np.dtype([("label", "U12"), ("value", float)])
np.loadtxt(s, dtype=dtype, delimiter=",", quotechar='"')

array([('alpha, #42', 10.), ('beta, #64',  2.)],
      dtype=[('label', '<U12'), ('value', '<f8')])

Two consecutive quote characters within a quoted field are treated as a single escaped character:

In [89]:
s = StringIO('"Hello, my name is ""Monty""!"')
np.loadtxt(s, dtype="U", delimiter=",", quotechar='"')

array('Hello, my name is"Monty"!', dtype='<U25')

## Creating Record Arrays (numpy.rec)