# Array Creation Routines
[Array creation](https://numpy.org/doc/stable/reference/routines.array-creation.html)

In [1]:
import numpy as np

## From Shape or Value

[`numpy.empty()`](https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty)

Return a new array of given shape and type without initializing entries.


In [2]:
np.empty([2,2])

array([[1.05977581e-311, 1.29061142e-306],
       [5.25685847e-321, 1.05887590e-311]])

In [3]:
np.empty([2,2], dtype=int)

array([[ -947457092, -1474180065],
       [-2079720577,  -474239255]])

[`numpy.empty_like()`](https://numpy.org/doc/stable/reference/generated/numpy.empty_like.html#numpy.empty_like)

Return a new array with the same shape and type as a given array.

In [4]:
a = ([1,2,3], [4,5,6])
np.empty_like(a)

array([[ 1864239920,         499,  1890520064],
       [        499,           0, -2147483648]])

In [5]:
a = ([1., 2., 3.], [4., 5., 6.])
np.empty_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

[`numpy.eye()`](https://numpy.org/doc/stable/reference/generated/numpy.eye.html)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [6]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [7]:
np.eye(3, k=1) # k is index of diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
np.eye(3, 5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

[`numpy.identity()`](https://numpy.org/doc/stable/reference/generated/numpy.identity.html)

Return the identity array. **The identity array is a square array with ones on the main diagonal and zeros elsewhere.**

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

[`numpy.ones()`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

Return a new array of given shape and type, filled with ones.

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [13]:
np.ones((2,1))

array([[1.],
       [1.]])

In [14]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

[`numpy.ones_like()`](https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html)

Return an array of zeros with the same shape and type as a given array.

In [15]:
x = np.arange(6)
x = x.reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
y = np.arange(3, dtype=float)
y

array([0., 1., 2.])

In [18]:
np.ones_like(y)

array([1., 1., 1.])

[`numpy.zeros()`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

Return a new array of given shape and type, filled with zeros.

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [21]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [22]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [23]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom type

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

[`numpy.zeros_like()`](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html)

Return an array of zeros with the same shape and type as a given array.

In [24]:
x = np.arange(6)
x = x.reshape((2,3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
y = np.arange(3, dtype=float)
y

array([0., 1., 2.])

In [26]:
np.zeros_like(y)

array([0., 0., 0.])

[`numpy.full()`](https://numpy.org/doc/stable/reference/generated/numpy.full.html)

Return a new array of given shape and type, filled with *fill_value*

In [27]:
np.full((2,2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [28]:
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [29]:
np.full((2,2), [1,2])

array([[1, 2],
       [1, 2]])

[`numpy.full_like()`](https://numpy.org/doc/stable/reference/generated/numpy.full_like.html)

Return a full array with the shape and type as a given array.

In [31]:
x = np.arange(6)
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

In [32]:
np.full_like(x, 0.1)

array([0, 0, 0, 0, 0, 0])

In [34]:
np.full_like(x, 0.1, dtype=np.double)

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [35]:
np.full_like(x, np.nan, dtype=np.double)

array([nan, nan, nan, nan, nan, nan])

In [38]:
y = np.arange(6, dtype=np.double)
np.full_like(y, 0.1)

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [39]:
y = np.zeros([2, 2, 3], dtype=int)
np.full_like(y, [0, 0, 255])

array([[[  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255]]])

## From existing data

[`numpy.array()`](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

Create an array.

In [40]:
np.array([1,2,3])

array([1, 2, 3])

In [41]:
np.array([1, 2, 3.0]) # upcasting

array([1., 2., 3.])

In [44]:
np.array([[1, 2], [3, 4]]) # more than one dimension

array([[1, 2],
       [3, 4]])

In [46]:
np.array([1,2,3], ndmin=2) # minimum 2 dimensions

array([[1, 2, 3]])

In [47]:
np.array([1, 2, 3], dtype=complex) # type provided

array([1.+0.j, 2.+0.j, 3.+0.j])

In [52]:
# data type consisting of more than one element
x = np.array([(1, 2), (3, 4)], dtype=[('a', '<i4'),('b', '<i4')])
x['a']

array([1, 3])

In [53]:
np.array(np.mat('1 2; 3 4')) # creating an array from sub-classes

array([[1, 2],
       [3, 4]])

In [55]:
np.array(np.mat('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

[`numpy.asarray()`](https://numpy.org/doc/stable/reference/generated/numpy.asarray.html)

Convert input into an array

In [56]:
np.asarray([1,2]) # converts list into an array

array([1, 2])

In [58]:
# if dtype is set, array is only copied if dtype does not match
a = np.asarray([1,2], dtype=np.float32) 
print(np.asarray(a, dtype=np.float32) is a)
print(np.asarray(a, dtype=np.float64) is a)

True
False


In [62]:
# contrary to asanyarray, ndarray subclasses are not passed through
print(issubclass(np.recarray, np.ndarray))
a = np.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(np.recarray)
print(np.asarray(a) is a)
print(np.asanyarray(a) is a)

True
False
True


[`numpy.asanyarray()`](https://numpy.org/doc/stable/reference/generated/numpy.asanyarray.html)

Convert the input to an ndarray, but pass ndarray subclasses through.

In [63]:
a = [1,2]
np.asanyarray(a)

array([1, 2])

In [64]:
a = np.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(np.recarray)
np.asanyarray(a) is a

True

[`numpy.ascontiguousarray()`](https://numpy.org/doc/stable/reference/generated/numpy.ascontiguousarray.html)

Return a contiguous array (ndim >= 1) in memory (C order)

In [65]:
x = np.arange(6).reshape(2,3)
np.ascontiguousarray(x, dtype=np.float32)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [66]:
x.flags['C_CONTIGUOUS']

True

[`numpy.copy()`](https://numpy.org/doc/stable/reference/generated/numpy.copy.html)

Return an array copy of given object

In [67]:
# Create an array x, with a reference y and copy z
x = np.array([1,2,3])
y = x
z = np.copy(x)

In [69]:
# Not that, when we modify x, y changes, but not z
x[0] = 10

x[0] == y[0]

True

In [70]:
x[0] == z[0]

False

In [71]:
# Note that, np.copy clears previously set WRITEABLE=False flag
a = np.array([1,2,3])
a.flags["WRITEABLE"] = False
b = np.copy(a)
b.flags["WRITEABLE"]

True

In [72]:
b[0] = 3
b

array([3, 2, 3])

Note that `np.copy()` is a shallow copy an will not copy object elements within arrays. This is mainly important for arrays containing Python objects. The new array will contain the same object which may lead to **surprises** if that object can be modified (is mutable).

In [73]:
a = np.array([1, 'm', [2,3,4]], dtype=object)
b = np.copy(a)
b[2][0] = 10
a

array([1, 'm', list([10, 3, 4])], dtype=object)

To ensure all elements within an `object` array are copied, use `copy.deepcopy()`

In [74]:
import copy
a = np.array([1, 'm', [2,3,4]], dtype=object)
c = copy.deepcopy(a)
c[2][0] = 10
c

array([1, 'm', list([10, 3, 4])], dtype=object)

In [75]:
a

array([1, 'm', list([2, 3, 4])], dtype=object)