# Binary Operations
[Binary Operations](https://numpy.org/doc/stable/reference/routines.bitwise.html)

In [1]:
import numpy as np

## Elementwise bit operations

[`np.bitwise_and`](https://numpy.org/doc/stable/reference/generated/numpy.bitwise_and.html)

Computes the bit-wise AND of two arrays element-wise.

In [2]:
np.bitwise_and(13, 17)

1

In [3]:
np.bitwise_and(14, 13)

12

In [4]:
np.binary_repr(12)

'1100'

In [5]:
np.bitwise_and([14,3], 13)

array([12,  1], dtype=int32)

In [6]:
np.bitwise_and([11, 7], [4,25])

array([0, 1], dtype=int32)

In [7]:
np.bitwise_and(np.array([2,5,255]), np.array([3,14,16]))

array([ 2,  4, 16], dtype=int32)

In [8]:
np.bitwise_and([True, True], [False, True])

array([False,  True])

The `&` operator can be used as a shorthand for `np.bitwise_and` on ndarrays.

In [9]:
x1 = np.array([2, 5, 255])
x2 = np.array([3, 14, 16])
x1 & x2

array([ 2,  4, 16], dtype=int32)

[`np.bitwise_or`](https://numpy.org/doc/stable/reference/generated/numpy.bitwise_or.html)

Compute the bit-wise OR of two arrays element-wise.

In [10]:
np.bitwise_or(13, 16)

29

In [11]:
np.binary_repr(29)

'11101'

In [12]:
np.bitwise_or(32, 2)

34

In [13]:
np.bitwise_or([33, 4], 1)

array([33,  5], dtype=int32)

In [14]:
np.bitwise_or([33,4], [1,2])

array([33,  6], dtype=int32)

In [15]:
np.bitwise_or(np.array([2,5,255]), np.array([4, 4, 4]))

array([  6,   5, 255], dtype=int32)

In [16]:
np.bitwise_or(
    np.array([2, 5, 255, 2147483647], dtype=np.int32),
    np.array([4, 4, 4, 214783647], dtype=np.int32)
)

array([         6,          5,        255, 2147483647], dtype=int32)

In [17]:
np.bitwise_or([True, True], [False,True])

array([ True,  True])

The `|` operator can be used as a shorthand for `np.bitwise_or` on ndarrays.

In [18]:
np.array([2,5,255]) | np.array([4,4,4])

array([  6,   5, 255], dtype=int32)

[`np.bitwise_xor`](https://numpy.org/doc/stable/reference/generated/numpy.bitwise_xor.html)

Compute the bit-wise XOR of two arrays element-wise.

In [19]:
np.bitwise_xor(13, 17)

28

In [20]:
np.binary_repr(28)

'11100'

In [21]:
np.bitwise_xor(31, 5)

26

In [22]:
np.bitwise_xor([31,3], 5)

array([26,  6], dtype=int32)

In [23]:
np.bitwise_xor([31,3], [5,6])

array([26,  5], dtype=int32)

In [24]:
np.bitwise_xor([True, True], [False, True])

array([ True, False])

The `^` Operator can be used as a shorthand for `np.bitwise_xor` on ndarrays.

In [25]:
np.array([True, True]) ^ np.array([False, True])

array([ True, False])

[`np.invert`](https://numpy.org/doc/stable/reference/generated/numpy.invert.html)

Compute bit-wise inverstion, or bit-wise NOT, element-wise.

`np.bitwise_not` is an alias for `np.invert`:

In [26]:
np.bitwise_not is np.invert

True

In [27]:
x = np.array(13, dtype=np.uint8)
np.binary_repr(x, width=8)

'00001101'

In [28]:
np.binary_repr(np.invert(x))

'11110010'

The result depends on bit-width:

In [29]:
x = np.array(13, dtype=np.uint16)
np.binary_repr(x, width=16)

'0000000000001101'

In [30]:
np.binary_repr(np.invert(x))

'1111111111110010'

In [31]:
np.invert(np.array([True, False]))

array([False,  True])

The `~` operator can be used as a shorthand for `np.invert` on ndarrays.

In [32]:
~np.array([True, False])

array([False,  True])

[`np.left_shift`](https://numpy.org/doc/stable/reference/generated/numpy.left_shift.html)

Shift the bits of an integer to the left.

Bits are shifted to the left by appending `x2` 0s at the right of `x1`. Since the internal representation of numbers is in binary format, this operation is equivalent to ultiplying `x1` by `2**x2`

In [33]:
np.binary_repr(5)

'101'

In [34]:
np.left_shift(5, 2)

20

In [35]:
np.binary_repr(20)

'10100'

In [36]:
np.left_shift(5, [1,2,3])

array([10, 20, 40], dtype=int32)

Note that the dtype of the second argument may change the dtype of the result and can lead to unexpected results in some cases:

In [37]:
a = np.left_shift(np.uint8(255), 1) # Expect 254
print(a, type(a)) # Unexpected result due to upcasting
b = np.left_shift(np.uint8(255), np.uint8(1))
print(b, type(b))

510 <class 'numpy.intc'>
254 <class 'numpy.uint8'>


The `<<` operator can be used as a shorthand for `np.left_shift` on ndarrays:

In [38]:
np.array(5) << np.array([1,2,3])

array([10, 20, 40], dtype=int32)

[`np.right_shift`](https://numpy.org/doc/stable/reference/generated/numpy.right_shift.html)

Shift the bits to the right `x2`. Because the internal representation of numbers is in binary format, this operation is equivalent to dividing `x1` by `2**x2`.

In [39]:
np.binary_repr(10)

'1010'

In [40]:
np.right_shift(10, 1)

5

In [41]:
np.binary_repr(5)

'101'

In [47]:
print(f"10 >> 1 = {np.right_shift(10, 1)}")

10 >> 1 = 5


In [48]:
np.right_shift(10, [1,2,3])

array([5, 2, 1], dtype=int32)

The `>>` operator can be used as a shorthand for `np.right_shift` on ndarrays.

In [49]:
np.array(10) >> np.array([1,2,3])

array([5, 2, 1], dtype=int32)

## Bit packing

[`np.packbits`](https://numpy.org/doc/stable/reference/generated/numpy.packbits.html)

Packs the elemants of a binary-valued array into bits in a uint8 array.

The result is padded to full bytes by inserting zero bits at the end.

In [50]:
a = np.array([[[1,0,1],
               [0,1,0]],
              [[1,1,0],
               [0,0,1]]])
b = np.packbits(a, axis=-1)
b

array([[[160],
        [ 64]],

       [[192],
        [ 32]]], dtype=uint8)

In [56]:
np.array([np.binary_repr(n, width=8) for n in b.flat]).reshape(b.shape)

array([[['10100000'],
        ['01000000']],

       [['11000000'],
        ['00100000']]], dtype='<U8')

[`np.unpackbits`](https://numpy.org/doc/stable/reference/generated/numpy.unpackbits.html)

Unpacks elements of a uint8 array into a binary-valued output array.

In [58]:
a = np.array([[2], [7], [23]], dtype=np.uint8)
a

array([[ 2],
       [ 7],
       [23]], dtype=uint8)

In [59]:
b = np.unpackbits(a, axis=1)
b

array([[0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 0, 1, 1, 1]], dtype=uint8)

In [61]:
c = np.unpackbits(a, axis=1, count=-3)
c

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0]], dtype=uint8)

In [62]:
p = np.packbits(b, axis=0)
np.unpackbits(p, axis=0)

array([[0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [63]:
np.array_equal(b, np.unpackbits(p, axis=0, count=b.shape[0]))

True

## Output formating

[`np.binary_repr`](https://numpy.org/doc/stable/reference/generated/numpy.binary_repr.html)

Return the binary representation of the input number a string.

In [64]:
np.binary_repr(3)

'11'

In [65]:
np.binary_repr(-3)

'-11'

In [66]:
np.binary_repr(3, width=4)

'0011'

The two's complement is returned when the input number is negative and width is specified:

In [67]:
np.binary_repr(-3, width=5)

'11101'

In [68]:
np.binary_repr(-3, width=5)

'11101'