# Array Manipulation Routines
[Array Manipulation Routines](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

In [1]:
import numpy as np

## Basic Operations

[`np.copyto`](https://numpy.org/doc/stable/reference/generated/numpy.copyto.html#numpy.copyto)

Copies values from one array to another, brodcasting as necessary.

In [2]:
A = np.array([4, 5, 6])
B = [1, 2, 3]
np.copyto(A, B)
A

array([1, 2, 3])

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = [[4, 5, 6], [7, 8, 9]]
np.copyto(A, B)
A

array([[4, 5, 6],
       [7, 8, 9]])

[`np.shape`](https://numpy.org/doc/stable/reference/generated/numpy.shape.html#numpy.shape)

Return shape of an array.

In [4]:
np.shape(np.eye(3))

(3, 3)

In [5]:
np.shape([[1,3]])

(1, 2)

In [6]:
np.shape([0])

(1,)

In [7]:
np.shape(0)

()

In [8]:
a = np.array([(1, 2), (3, 4), (5, 6)],
                dtype=[('x', 'i4'), ('y', 'i4')])
print(np.shape(a))
print(a.shape)

(3,)
(3,)


## Changing array shape

[`np.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

Gives a new shape to an array without changing its data.

In [9]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [11]:
np.reshape(a, 6, order='F')

array([1, 4, 2, 5, 3, 6])

In [12]:
np.reshape(a, (3,-1)) # the unspeified value is infered to be 2

array([[1, 2],
       [3, 4],
       [5, 6]])

[`np.ravel`](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html)

Returns a contiguous flattened array.

In [13]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [15]:
np.ravel(x, order='F')

array([1, 4, 2, 5, 3, 6])

When `order` is 'A', it will preserve the array's 'C' or 'F' ordering:

In [16]:
np.ravel(x.T)

array([1, 4, 2, 5, 3, 6])

In [17]:
np.ravel(x.T, order='A')

array([1, 2, 3, 4, 5, 6])

Wher `order` is 'K', it will preserve orderings that are neither 'C' or 'F', but won't reverse axes:

In [18]:
a = np.arange(3)[::-1]; a

array([2, 1, 0])

In [19]:
a.ravel(order='C')

array([2, 1, 0])

In [20]:
a.ravel(order='K')

array([2, 1, 0])

In [21]:
a = np.arange(12).reshape(2,3,2).swapaxes(1,2); a

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [22]:
a.ravel(order='C')

array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11])

In [23]:
a.ravel(order='K')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

[`np.ndarray.flat`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flat.html#numpy.ndarray.flat)

A 1-D iterator over the array.

In [24]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
x.flat[3]

4

In [26]:
x.T.flat[3]

5

In [27]:
type(x.flat)

numpy.flatiter

An assignment example:

In [28]:
x.flat = 3; x

array([[3, 3, 3],
       [3, 3, 3]])

In [29]:
x.flat[[1,4]] = 1; x

array([[3, 1, 3],
       [3, 1, 3]])

[`np.ndarray.flatten`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten)

Return a copy of the array collepsed into one dimension.

In [30]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [31]:
a.flatten('F')

array([1, 3, 2, 4])

## Transpose-like operations

[`np.moveaxis`](https://numpy.org/doc/stable/reference/generated/numpy.moveaxis.html#numpy.moveaxis)

Move axes of an array to new positions. Other axes remain in their original order.

In [32]:
x = np.zeros((3, 4, 5))
x.shape

(3, 4, 5)

In [33]:
np.moveaxis(x, 0, -1).shape

(4, 5, 3)

In [34]:
np.moveaxis(x, -1, 0).shape

(5, 3, 4)

These all achieve the same result:

In [35]:
np.transpose(x).shape

(5, 4, 3)

In [36]:
np.swapaxes(x, 0, -1).shape

(5, 4, 3)

In [37]:
np.moveaxis(x, [0,1], [-1,-2]).shape

(5, 4, 3)

In [38]:
np.moveaxis(x, [0,1,2], [-1, -2, -3]).shape

(5, 4, 3)

more examples:

In [39]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [40]:
np.moveaxis(a, 0, -1)

array([[[ 0,  6],
        [ 1,  7]],

       [[ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11]]])

In [41]:
np.moveaxis(a, 1, 0)

array([[[ 0,  1],
        [ 6,  7]],

       [[ 2,  3],
        [ 8,  9]],

       [[ 4,  5],
        [10, 11]]])

[`np.rollaxis`](https://numpy.org/doc/stable/reference/generated/numpy.rollaxis.html)

Roll the specified axis backwards, until it lies in a given position.

In [42]:
a = np.ones((3,4,5,6))
np.rollaxis(a, 3, 1).shape

(3, 6, 4, 5)

In [43]:
np.rollaxis(a, 2).shape

(5, 3, 4, 6)

In [44]:
np.rollaxis(a, 1, 4).shape

(3, 5, 6, 4)

[`np.swapaxes`](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html)

Interchange two axes of an array.

In [45]:
x = np.array([[1,2,3]])
np.swapaxes(x, 0, 1)

array([[1],
       [2],
       [3]])

In [46]:
x = np.array([[[0,1], [2,3]], [[4,5], [6,7]]])
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [47]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

[`np.ndarray.T`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html#numpy.ndarray.T)

View of the transposed array.

In [48]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [49]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [50]:
a.T

array([1, 2, 3, 4])

[`np.transpose`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html#numpy.transpose)

Returns an array with axes transposed.

In [51]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [52]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [53]:
np.transpose(a)

array([1, 2, 3, 4])

In [54]:
a = np.ones((1, 2 ,3))
np.transpose(a, (1, 0, 2)).shape

(2, 1, 3)

In [55]:
a = np.ones((2,3,4,5))
np.transpose(a).shape

(5, 4, 3, 2)

## Changing number of dimensions

[`np.atleast_1d`](https://numpy.org/doc/stable/reference/generated/numpy.atleast_1d.html#numpy.atleast_1d)

Converts inputs to arrays with at least one dimension.

In [57]:
np.atleast_1d(1.0)

array([1.])

In [58]:
x = np.arange(9.0).reshape(3,3)
np.atleast_1d(x)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [59]:
np.atleast_1d(x) is x

True

[`np.atleast_2d`](https://numpy.org/doc/stable/reference/generated/numpy.atleast_2d.html)

View inputs as arrays with at least two dimensions.

In [60]:
np.atleast_2d(3.0)

array([[3.]])

In [61]:
x = np.arange(3.0)
np.atleast_2d(x)

array([[0., 1., 2.]])

In [62]:
np.atleast_2d(x) is x

False

In [63]:
np.atleast_2d(x).base is x

True

In [64]:
np.atleast_2d(1, [1,2], [[1,2]])

[array([[1]]), array([[1, 2]]), array([[1, 2]])]

[`np.atleast_3d`](https://numpy.org/doc/stable/reference/generated/numpy.atleast_3d.html#numpy.atleast_3d)

View inputs as arrays with at least three dimensions.

In [65]:
np.atleast_3d(3.0)

array([[[3.]]])

In [66]:
x = np.arange(3.0)
np.atleast_3d(x).shape

(1, 3, 1)

In [67]:
x = np.arange(12.0).reshape(4,3)
np.atleast_3d(x).shape

(4, 3, 1)

In [68]:
# x is a reshape, so not base itself
np.atleast_3d(x).base is x.base

True

In [71]:
for arr in np.atleast_3d([1,2], [[1,2]], [[[1,2]]]):
    print(arr, arr.shape, "\n")

[[[1]
  [2]]] (1, 2, 1) 

[[[1]
  [2]]] (1, 2, 1) 

[[[1 2]]] (1, 1, 2) 



[`np.broadcast`](https://numpy.org/doc/stable/reference/generated/numpy.broadcast.html#numpy.broadcast)

Produce an object that mimics brodcasting.

In [74]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
b

In [76]:
out = np.empty(b.shape)
out.flat = [u+v for (u,v) in b]
out

array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

Compare against built-in broadcasting:

In [77]:
x + y

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

[`np.broadcast_to`](https://numpy.org/doc/stable/reference/generated/numpy.broadcast_to.html)

Broadcast an array to a new shape.

In [78]:
x = np.array([1,2,3])
np.broadcast_to(x, (3,3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

[`np.broadcast_arrays`](https://numpy.org/doc/stable/reference/generated/numpy.broadcast_arrays.html)

Broadcast any number of arrays against each other.

In [80]:
x = np.array([[1,2,3]])
y = np.array([[4], [5]])
np.broadcast_arrays(x, y)

[array([[1, 2, 3],
        [1, 2, 3]]),
 array([[4, 4, 4],
        [5, 5, 5]])]

Here is a useful idiom for getting contiguous copies instead of non-contiguous views.

In [81]:
[np.array(a) for a in np.broadcast_arrays(x, y)]

[array([[1, 2, 3],
        [1, 2, 3]]),
 array([[4, 4, 4],
        [5, 5, 5]])]

[`np.expand_dims`](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html)

Expand the shape of an array.

In [82]:
x = np.array([1, 2])
x.shape

(2,)

The following is equivalent to `x[np.newaxis, :]` or `x[np.newaxis]`:

In [84]:
y = np.expand_dims(x, axis=0)
y

array([[1, 2]])

In [85]:
y.shape

(1, 2)

The following is equivalent to `x[:, np.newaxis]`

In [86]:
y = np.expand_dims(x, axis=1)
y

array([[1],
       [2]])

In [87]:
y.shape

(2, 1)

`axis` may also be a tuple:

In [83]:
y = np.expand_dims(x, axis=(0,1))
y

array([[[1, 2]]])

In [89]:
y = np.expand_dims(x, axis=(2,0))
y

array([[[1],
        [2]]])

Note that some examples may use `None` instead of `np.newaxis`. These are the same objects.

In [90]:
np.newaxis is None

True

[`np.squeeze`](https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html)

Remove axes of length one from a.

In [91]:
x = np.array([[[0], [1], [2]]])
x.shape

(1, 3, 1)

In [92]:
np.squeeze(x, axis=0).shape

(3, 1)

In [93]:
np.squeeze(x, axis=1).shape # error on purpose

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [94]:
np.squeeze(x, axis=2).shape

(1, 3)

In [95]:
x = np.array([[1234]])
x.shape

(1, 1)

In [96]:
np.squeeze(x)

array(1234)

In [97]:
np.squeeze(x)

array(1234)

In [98]:
np.squeeze(x).shape

()

In [99]:
np.squeeze(x)[()]

1234